[vlive_notice]
title = "aespa ─ Notice"
url = "https://vlive.tv/channel/97CCED/board/7374"
entrySelector = "//html/body/div/div/div/div[2]/div[3]/div[2]/ul/li"
titleSelector = "//a/div/div[1]/div[1]/strong"
linkSelector = "//a[@class='post_area--1y4Lh']"
contentSelector = "//div[1]/div/a/div[2]/div[1]/em"
dateSelector = "//div[1]/div/a/div[2]/div[2]/div/span"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[vlive_news]
title = "aespa ─ News"
url = "https://www.vlive.tv/channel/97CCED/board/7387"
entrySelector = "//html/body/div/div/div/div[2]/div[3]/div[2]/ul/li[contains(@class,'post_item')]"
titleSelector = "//a/div/div[1]/div/strong"
linkSelector = "//a[@class='post_area--3dKbo']"
contentSelector = "//div[1]/div/a/div[2]/div[1]/em"
dateSelector = "//div[1]/div/a/div[2]/div[2]/div/span"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[vlive_my]
title = "aespa ─ MY"
url = "https://www.vlive.tv/channel/97CCED/board/7375"
entrySelector = "//html/body/div/div/div/div[2]/div[3]/div[2]/ul/li[contains(@class,'post_item')]"
titleSelector = "//a/div/div[1]/div/strong"
linkSelector = "//a[@class='post_area--3dKbo']"
contentSelector = "//div[1]/div/a/div[2]/div[1]/em"
dateSelector = "//div[1]/div/a/div[2]/div[2]/div/span"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[vlive_letter]
title = "aespa ─ aespa Letter"
url = "https://www.vlive.tv/channel/97CCED/board/7553"
entrySelector = "//html/body/div/div/div/div[2]/div[3]/div[2]/ul/li[contains(@class,'post_item')]"
titleSelector = "//a/div/div[1]/div/strong"
linkSelector = "//a[@class='post_area--3dKbo']"
contentSelector = "//div[1]/div/a/div[2]/div[1]/em"
dateSelector = "//div[1]/div/a/div[2]/div[2]/div/span"
dateFormat = "M.d."
waitUntil = "networkidle"
onFail = "stale"

[smtown_news]
title = "SMTOWN ─ aespa"
url = "https://www.smtown.com/search?type=sub_news&keyword=%EC%97%90%EC%8A%A4%ED%8C%8C"
entrySelector = "ul.search_news.artist li"
titleSelector = "span.title"
linkSelector = "a.btn_text"
imageSelector = "a[class='btn_img bg_cover']"
contentSelector = "span.text"
waitUntil = "networkidle"
